version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_trad
    volumes:
      - ./bdd:/var/lib/mysql
    ports:
      - "3307:3306"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data:

